### ISSUE TITLE
Invalid host

### ISSUE THREAD

**Issue by Nacsis** [JoergZ2/my-tasmota-de-skill#1]
Hi, 

Ich habe den Skill installiert und in settingsmeta.yaml die IP und den Port angegeben. Der MQTT Broker läuft auf dem selben Raspberry Pi, wie die Mycroft Instanz.

Ich habe die IP und auch localhost jeweils mit und ohne Anführungszeichen getestet. Jeweils mit dem Satz "Schalte Schalter an".

Leider bricht der Vorgang mit einer Fehlermeldung ab:

` 
13:08:08.462 | INFO     | 27304 | my-tasmota-de-skill | AJW - Module automation_command connect to: 1883
 13:08:09.476 | ERROR    | 27304 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:835 | Bei der Verarbeitung der Anfrage ist ein Fehler im Skill My Tasmota De aufgetreten.
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft/skills/my-tasmota-de-skill/__init__.py", line 217, in handle_automation_command
    self.mqttc.connect(self.mqtthost, self.mqttport, keepalive=10)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 940, in connect
    bind_address, bind_port, clean_start, properties)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 1005, in connect_async
    raise ValueError('Invalid host.')
ValueError: Invalid host.
`

Habe ich den Host an der falschen Stelle bzw falsch definiert? 

Gruß,

Nacsis

**Comment by Nacsis** [comment]
Okay, ich habe es zum laufen bekommen über die Konfiguration auf home.mycroft.ai
